from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import time
import datetime
import os


class Ui_TBRD(object):
    def setupUi(self, TBRD):
        TBRD.setObjectName("TBRD")
        TBRD.setWindowModality(QtCore.Qt.NonModal)
        TBRD.setEnabled(True)
        TBRD.resize(711, 564)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TBRD.sizePolicy().hasHeightForWidth())
        TBRD.setSizePolicy(sizePolicy)
        TBRD.setMouseTracking(False)
        TBRD.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(TBRD)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Dutch801 Rm BT")
        font.setPointSize(14)
        self.title.setFont(font)
        self.title.setFrameShape(QtWidgets.QFrame.Panel)
        self.title.setMidLineWidth(0)
        self.title.setScaledContents(False)
        self.title.setObjectName("title")
        self.verticalLayout_6.addWidget(self.title)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.name_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Dutch801 Rm BT")
        font.setPointSize(14)
        self.name_title.setFont(font)
        self.name_title.setObjectName("name_title")
        self.verticalLayout_4.addWidget(self.name_title)
        self.age_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Dutch801 Rm BT")
        font.setPointSize(14)
        self.age_title.setFont(font)
        self.age_title.setObjectName("age_title")
        self.verticalLayout_4.addWidget(self.age_title)
        self.phone_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Dutch801 Rm BT")
        font.setPointSize(14)
        self.phone_title.setFont(font)
        self.phone_title.setObjectName("phone_title")
        self.verticalLayout_4.addWidget(self.phone_title)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.fullname_txtbox = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Dutch801 Rm BT")
        font.setPointSize(14)
        self.fullname_txtbox.setFont(font)
        self.fullname_txtbox.setObjectName("fullname_txtbox")
        self.verticalLayout_5.addWidget(self.fullname_txtbox)
        self.age_txtbox = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Dutch801 Rm BT")
        font.setPointSize(14)
        self.age_txtbox.setFont(font)
        self.age_txtbox.setObjectName("age_txtbox")
        self.verticalLayout_5.addWidget(self.age_txtbox)
        self.phone_txtbox = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Dutch801 Rm BT")
        font.setPointSize(14)
        self.phone_txtbox.setFont(font)
        self.phone_txtbox.setObjectName("phone_txtbox")
        self.verticalLayout_5.addWidget(self.phone_txtbox)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_5)
        self.gender_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Dutch801 Rm BT")
        font.setPointSize(14)
        self.gender_title.setFont(font)
        self.gender_title.setObjectName("gender_title")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.gender_title)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.male_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.male_radioButton.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setFamily("Dutch801 Rm BT")
        font.setPointSize(14)
        self.male_radioButton.setFont(font)
        self.male_radioButton.setObjectName("male_radioButton")
        self.verticalLayout_3.addWidget(self.male_radioButton)
        self.female_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Dutch801 Rm BT")
        font.setPointSize(14)
        self.female_radioButton.setFont(font)
        self.female_radioButton.setObjectName("female_radioButton")
        self.verticalLayout_3.addWidget(self.female_radioButton)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.formLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.clicked.connect(self.start_btn_func)
        # self.start_btn.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Dutch801 Rm BT")
        font.setPointSize(14)
        self.start_btn.setFont(font)
        self.start_btn.setObjectName("start_btn")
        self.verticalLayout_2.addWidget(self.start_btn)

        self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_btn.clicked.connect(self.stop_btn_func)
        self.stop_btn.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Dutch801 Rm BT")
        font.setPointSize(14)
        self.stop_btn.setFont(font)
        self.stop_btn.setObjectName("stop_btn")
        self.verticalLayout_2.addWidget(self.stop_btn)

        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.test_time_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Dutch801 Rm BT")
        font.setPointSize(14)
        self.test_time_title.setFont(font)
        self.test_time_title.setObjectName("test_time_title")
        self.verticalLayout.addWidget(self.test_time_title)

        self.testtime_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Dutch801 Rm BT")
        font.setPointSize(14)
        self.testtime_lcd.setFont(font)
        self.testtime_lcd.setFrameShape(QtWidgets.QFrame.Box)
        self.testtime_lcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.testtime_lcd.setSmallDecimalPoint(False)
        self.testtime_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.testtime_lcd.setObjectName("testtime_lcd")
        self.verticalLayout.addWidget(self.testtime_lcd)

        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.title.raise_()
        TBRD.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TBRD)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 711, 25))
        self.menubar.setObjectName("menubar")
        TBRD.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TBRD)
        self.statusbar.setObjectName("statusbar")
        TBRD.setStatusBar(self.statusbar)

        self.retranslateUi(TBRD)
        QtCore.QMetaObject.connectSlotsByName(TBRD)
        TBRD.setTabOrder(self.fullname_txtbox, self.start_btn)
        TBRD.setTabOrder(self.start_btn, self.male_radioButton)
        TBRD.setTabOrder(self.male_radioButton, self.female_radioButton)
        TBRD.setTabOrder(self.female_radioButton, self.age_txtbox)
        TBRD.setTabOrder(self.age_txtbox, self.phone_txtbox)
        TBRD.setTabOrder(self.phone_txtbox, self.stop_btn)

    def retranslateUi(self, TBRD):
        _translate = QtCore.QCoreApplication.translate
        TBRD.setWindowTitle(_translate("TBRD", "MainWindow"))
        self.title.setText(_translate("TBRD", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#aa0000;\">TBRD Interface</span></p></body></html>"))
        self.name_title.setText(_translate("TBRD", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">full name:</span></p></body></html>"))
        self.age_title.setText(_translate("TBRD", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">age:</span></p></body></html>"))
        self.phone_title.setText(_translate("TBRD", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">phone:</span></p></body></html>"))
        self.gender_title.setText(_translate("TBRD", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">gender:</span></p></body></html>"))
        self.male_radioButton.setText(_translate("TBRD", "Male"))
        self.female_radioButton.setText(_translate("TBRD", "Female"))
        self.start_btn.setText(_translate("TBRD", "Start"))
        self.stop_btn.setText(_translate("TBRD", "Stop"))
        self.test_time_title.setText(_translate("TBRD", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">test time</span></p></body></html>"))

    def start_btn_func(self):
        print('start recording!')
        if self.male_radioButton.isChecked(): gender = 'male'
        else : gender = 'female'
        self.file = open(os.path.join(directory, str(self.fullname_txtbox.text() + '_' + datetime.datetime.now().strftime("%I_%M_%p_%B_%d_%Y") + '.csv')), "w") 
        self.file.write(str(self.fullname_txtbox.text() + ',' + self.age_txtbox.text() + ',' + self.phone_txtbox.text() + ',' + gender + '\n'))
        # TODO log data
        self.start_btn.setEnabled(False)
        self.stop_btn.setEnabled(True)

    def stop_btn_func(self):
        # self.file.write(str(str(int(self.Ttime//60))+':'+str(int(self.Ttime%60)))) 
        self.file.close()
        print('recording is stopped!')
        self.fullname_txtbox.clear()
        self.age_txtbox.clear()
        self.phone_txtbox.clear()
        self.start_btn.setEnabled(True)
        self.stop_btn.setEnabled(False)



if __name__ == "__main__":
    
    path = os.getcwd()
    directory = str(os.path.join(path, 'data'))
    if not os.path.exists(directory):
        os.makedirs(directory)


    app = QtWidgets.QApplication(sys.argv)
    TBRD = QtWidgets.QMainWindow()
    ui = Ui_TBRD()
    ui.setupUi(TBRD)
    TBRD.show()
    sys.exit(app.exec_())

